export const ApiData = [{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/3-99_394x.webp?v=1679585927",
    "url": "https://endocollects.co.uk/products/paldea-evolved-elite-trainer-box",
    "title": "PALDEA EVOLVED - ELITE TRAINER BOX",
    "price": "39.50",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/IMG_1969_394x.jpg?v=1679625814",
    "url": "https://endocollects.co.uk/collections/paldea-evolved/products/paldea-evolved-triple-blister",
    "title": "PALDEA EVOLVED - TRIPLE BLISTER",
    "price": "13.00",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/Paldea-Legends-Tins-Miraidon-ex-scaled_394x.jpg?v=1679586977",
    "url": "https://endocollects.co.uk/collections/paldea-evolved/products/paldea-legends-collection-tins",
    "title": "PALDEA LEGENDS COLLECTION TINS",
    "price": "19.50",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/3-99_394x.webp?v=1679585927",
    "url": "https://endocollects.co.uk/products/paldea-evolved-elite-trainer-box",
    "title": "PALDEA EVOLVED - ELITE TRAINER BOX",
    "price": "39.50",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/IMG_1969_394x.jpg?v=1679625814",
    "url": "https://endocollects.co.uk/collections/paldea-evolved/products/paldea-evolved-triple-blister",
    "title": "PALDEA EVOLVED - TRIPLE BLISTER",
    "price": "13.00",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/Paldea-Legends-Tins-Miraidon-ex-scaled_394x.jpg?v=1679586977",
    "url": "https://endocollects.co.uk/collections/paldea-evolved/products/paldea-legends-collection-tins",
    "title": "PALDEA LEGENDS COLLECTION TINS",
    "price": "19.50",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
}, {
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/3-99_394x.webp?v=1679585927",
    "url": "https://endocollects.co.uk/products/paldea-evolved-elite-trainer-box",
    "title": "PALDEA EVOLVED - ELITE TRAINER BOX",
    "price": "39.50",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/IMG_1969_394x.jpg?v=1679625814",
    "url": "https://endocollects.co.uk/collections/paldea-evolved/products/paldea-evolved-triple-blister",
    "title": "PALDEA EVOLVED - TRIPLE BLISTER",
    "price": "13.00",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/Paldea-Legends-Tins-Miraidon-ex-scaled_394x.jpg?v=1679586977",
    "url": "https://endocollects.co.uk/collections/paldea-evolved/products/paldea-legends-collection-tins",
    "title": "PALDEA LEGENDS COLLECTION TINS",
    "price": "19.50",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
}
    , {
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/3-99_394x.webp?v=1679585927",
    "url": "https://endocollects.co.uk/products/paldea-evolved-elite-trainer-box",
    "title": "PALDEA EVOLVED - ELITE TRAINER BOX",
    "price": "39.50",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/IMG_1969_394x.jpg?v=1679625814",
    "url": "https://endocollects.co.uk/collections/paldea-evolved/products/paldea-evolved-triple-blister",
    "title": "PALDEA EVOLVED - TRIPLE BLISTER",
    "price": "13.00",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/Paldea-Legends-Tins-Miraidon-ex-scaled_394x.jpg?v=1679586977",
    "url": "https://endocollects.co.uk/collections/paldea-evolved/products/paldea-legends-collection-tins",
    "title": "PALDEA LEGENDS COLLECTION TINS",
    "price": "19.50",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
}
    , {
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/3-99_394x.webp?v=1679585927",
    "url": "https://endocollects.co.uk/products/paldea-evolved-elite-trainer-box",
    "title": "PALDEA EVOLVED - ELITE TRAINER BOX",
    "price": "39.50",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/IMG_1969_394x.jpg?v=1679625814",
    "url": "https://endocollects.co.uk/collections/paldea-evolved/products/paldea-evolved-triple-blister",
    "title": "PALDEA EVOLVED - TRIPLE BLISTER",
    "price": "13.00",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/Paldea-Legends-Tins-Miraidon-ex-scaled_394x.jpg?v=1679586977",
    "url": "https://endocollects.co.uk/collections/paldea-evolved/products/paldea-legends-collection-tins",
    "title": "PALDEA LEGENDS COLLECTION TINS",
    "price": "19.50",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
}
    , {
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/3-99_394x.webp?v=1679585927",
    "url": "https://endocollects.co.uk/products/paldea-evolved-elite-trainer-box",
    "title": "PALDEA EVOLVED - ELITE TRAINER BOX",
    "price": "39.50",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/IMG_1969_394x.jpg?v=1679625814",
    "url": "https://endocollects.co.uk/collections/paldea-evolved/products/paldea-evolved-triple-blister",
    "title": "PALDEA EVOLVED - TRIPLE BLISTER",
    "price": "13.00",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
},
{
    "image": "https://cdn.shopify.com/s/files/1/0511/1224/7489/products/Paldea-Legends-Tins-Miraidon-ex-scaled_394x.jpg?v=1679586977",
    "url": "https://endocollects.co.uk/collections/paldea-evolved/products/paldea-legends-collection-tins",
    "title": "PALDEA LEGENDS COLLECTION TINS",
    "price": "19.50",
    "site": "Endo Collects",
    "siteUrl": "https://endocollects.co.uk/",
}]